// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_name_ from "./routes/[name].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_sync from "./routes/api/sync.ts";
import * as $index from "./routes/index.tsx";
import * as $Board from "./islands/Board.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[name].tsx": $_name_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/sync.ts": $api_sync,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Board.tsx": $Board,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
